Import('build_env')

env = build_env.Clone()
env.UseLibraries(['libposix', 'libstd', 'libarch', 'libipc', 'libfs' ])
env.UseServers(['core', 'filesystem'])
env.TargetLibrary('libmpi', [ Glob('*.cpp') ])
