Import('build_env')

env = build_env.Clone()
env.UseServers(['log', 'filesystem', 'core', 'video'])
env.UseLibraries([ 'libposix', 'liballoc', 'libteken', 'libstd', 'libarch', 'libexec', 'libipc', 'libfs' ])

if env['ARCH'] == 'intel':
    env.TargetProgram('server', [ Glob('*.cpp') ])
