Import('build_env')

env = build_env.Clone()
env.UseServers(['core'])
env.UseLibraries(['liballoc', 'libstd'])
env.Append(CPPPATH = [ '.' ])

if env['ARCH'] == 'host':
    src = []
else:
    src = [ Glob('*.cpp'),
            Glob( env['ARCH'] + '/*.cpp'),
            Glob( env['ARCH'] + '/*.S'),
            Glob( env['ARCH'] + '/**/*.cpp'),
            Glob( env['ARCH'] + '/**/*.S') ]

env.Library('libarch', src)
