Import('build_env')

env = build_env.Clone()
env.UseServers(['filesystem'])
env.UseLibraries(['libposix', 'libstd', 'libarch'])
env.UseLibraries(['libstd', 'libarch'], 'host')
env.Library('libexec', [ Glob('*.cpp') ])
