Import('build_env')

env = build_env.Clone()
env.Append(CCFLAGS = [ '-DTEKEN_XTERM' ])
env.UseLibraries(['libposix', 'libstd'])
env.UseLibraries(['libstd'], 'host')
env.UseServers([ 'terminal', 'process' ])
env.Library('libteken', [ Glob('*.c') ])
