Import('build_env')

env = build_env.Clone()
env.UseLibraries([ 'libstd', 'libarch', 'liballoc' ])
env.UseLibraries([ 'libstd', 'libarch', 'liballoc' ], 'host')
env.UseServers([ 'core' ])

if env['ARCH'] == 'host':
    src = [ 'BubbleAllocator.cpp', 'Allocator.cpp' ]
else:
    src = Glob('*.cpp')

env.Library('liballoc', src)
