Import('build_env')

env = build_env.Clone()
env.UseServers(['log', 'filesystem', 'core'])
env.UseLibraries([ 'libposix', 'liballoc', 'libstd', 'libarch', 'libexec', 'libipc', 'libfs' ])

#
# TODO: convert to libpci
#
#env.TargetProgram('server', [ 'PCIServer.cpp', 'PCIRegister.cpp', 'PCIConfig.cpp' ])
#env.TargetProgram('detect', [ 'PCIDetect.cpp' ])

