Import('build_env')

env = build_env.Clone()
env.UseServers(['log', 'filesystem', 'core'])
env.UseLibraries([ 'libposix', 'liballoc', 'libstd', 'libexec', 'libarch', 'libipc'])
env.TargetProgram('server', [ Glob('*.cpp') ])
